version: "3.8"
services:
  db:
    image: rethinkdb:${RETHINKDB_IMAGE_TAG:-2.3.7}
    restart: unless-stopped
    container_name: db
    ports:
      - "${DB_ADMIN_PORT:-8080}:8080"
    volumes:
      - db-data:/data
    networks:
      - rethinkdb-backup-network
  dbbackup:
    image: rethinkdb-backup:latest
    restart: unless-stopped
    container_name: dbbackup
    ports:
      - "${RETHINKDB_BACKUP_PORT:-3000}:3000"
    volumes:
      - db-archives:/home/appuser/app/${DUMP_DIRECTORY:-archives}
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DUMP_DIRECTORY: ${DUMP_DIRECTORY:-archives}
    networks:
      - rethinkdb-backup-network

volumes:
  db-data:
  db-archives:

networks:
  rethinkdb-backup-network:
    driver: bridge
